### ISSUE TITLE
How do you draw the result images?

### ISSUE THREAD

**Issue by hubutui** [wulalago/DAF3D#1]
Hey, the fig 9 & 10 in the paper is awesome! Could you give me some guide or tutorial about how to draw something like these? Thanks!

**Comment by wulalago** [comment]
> Hey, the fig 9 & 10 in the paper is awesome! Could you give me some guide or tutorial about how to draw something like these? Thanks!

The fig 10 was drew by 3DMeshMetric that you can download in https://www.nitrc.org/projects/meshmetric3d/
Both MeshLab and Paraview can draw a similar effect of fig9, you can try it both.

**Comment by hubutui** [comment]
Thanks. And what the input image type of 3DMeshMetric? I have the ground truth of a 3D volume in `nii.gz` format, and I convert it to vtk format using SimpleITK's `sitk.WriteImage(data, 'result.vk')`. However, when I'm trying to import the vtk files to 3DMeshMetric, I get ` Structured_points cannot be read ` error.

**Comment by wulalago** [comment]
> Thanks. And what the input image type of 3DMeshMetric? I have the ground truth of a 3D volume in `nii.gz` format, and I convert it to vtk format using SimpleITK's `sitk.WriteImage(data, 'result.vk')`. However, when I'm trying to import the vtk files to 3DMeshMetric, I get `Structured_points cannot be read` error.

the avg distance 3DMeshMetric calculate is the surface distance, so you need to transfer the nifi image to the surface file. My suggestion is you can transfer the nifi image to the stl file through ITK-SNAP(segmentation -> Export as Surface Mesh).

**Comment by hubutui** [comment]
OK, thanks. Now I got it.
