### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by crh19970307** [wulalago/DAF3D#4]
Hi, thanks for publishing your code. I want to know where I can download the dataset in origin paper? Thanks!

**Comment by wulalago** [comment]
Hi, I am sorry we cannot share with you because the dataset is privately-owned. I suggest you can validate this method on other public medical dataset and I think it could also perform good. Thanks for your intesting our work, I am willing to answer if you have any other questions.

**Comment by wulalago** [comment]
> Hi, thanks for publishing your code. I want to know where I can download the dataset in origin paper? Thanks!

Hi, I am sorry we cannot share with you because the dataset is privately-owned. I suggest you can validate this method on other public medical dataset and I think it could also perform good. Thanks for your intesting our work, I am willing to answer if you have any other questions.
