### ISSUE TITLE
您好，请教一个论文里面的问题，有关可视化3d的。

### ISSUE THREAD

**Issue by lllllllllllll-llll** [wulalago/DAF3D#5]
论文里面的图片9和10是用什么做出来的呢？是直接把网络输出的矩阵经过可视化还是通过什么软件呢？

**Comment by wulalago** [comment]
通过3DMeshMetric这个软件可以画surface distance error map

**Comment by wulalago** [comment]
> 论文里面的图片9和10是用什么做出来的呢？是直接把网络输出的矩阵经过可视化还是通过什么软件呢？

通过3DMeshMetric这个软件可以画surface distance error map
